version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "5200:5200" # http
#     # file with environment declarations for the container
#     env_file:
#       - docker/web/.env
    # Link to containers in another service
    links:
      - db
    # sync workspace folder with /go
    volumes:
     - ./:/go
  db:
    image: image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: aicam
      MYSQL_PASSWORD: 021021ali
      MYSQL_ROOT_PASSWORD: 021021ali
      MYSQL_DATABASE: cryptodb
    # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
    # folder is at workspace root.
    volumes:
      - ./_local_mysql_data:/var/lib/mysql